#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

cat > /var/www/html/index.html << EOF
Hello World.
This is my first nginx image.
EOF

cat > /etc/nginx/nginx.conf <<EOF
worker_processes auto;
worker_rlimit_nofile 100000;
user www-data;

# only log critical errors
error_log /var/log/nginx/error.log crit;

events {
    worker_connections 4000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /var/log/nginx/access.log;

    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay on;
    types_hash_max_size 2048;
    server_tokens off;

    open_file_cache max=200000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    keepalive_timeout  60;
    reset_timedout_connection on;
    client_body_timeout 10;
    client_body_buffer_size  128k;
    large_client_header_buffers 4 256k;
    client_header_timeout 3m;
    send_timeout 2;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 10240;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied expired no-cache no-store private auth;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
EOF

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen   80 default_server;
    root /var/www/html;
    index index.php index.html index.htm;
    server_name _;

    access_log  /var/log/nginx/www.access.log;
    error_log  /var/log/nginx/www.error.log notice;

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    include /etc/nginx/conf.d/tuning;

    set \$no_cache 0;

    location / {
        try_files \$uri \$uri/ /index.php?\$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param   SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_cache_bypass \$no_cache;
        fastcgi_no_cache \$no_cache;
        fastcgi_cache cache;
        fastcgi_cache_valid 200 10m;
    }

    if (\$http_cookie = "PHPSESSID")
    {
        set \$no_cache 1;
    }
}
EOF

cat > /var/www/50x.html <<EOF
<h1>500 Internal Server Error</h1>
EOF

cat > /var/www/404.html <<EOF
<h1>Not found</h1>
EOF

systemctl enable nginx